
spring:
  application:
    name: config-client
  #  data:
  #    mongodb:
  #      uri: mongodb://localhost:27017/gallerydb


---
spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true




server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true