spring:
  application:
    name: eureka-client  # ??? ?? ?? UI http://localhost:8761/ ???????????? Application ???


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} # 1 ??????? ????? ??????? ? ??????? eureka (serviceUrl)
    eureka-service-url-poll-interval-seconds: 35 # 3 ??????? ???????? ? 35 ??? ????? ??????? ?????? ???? ??? ?????? ?? ??????
  instance:
    preferIpAddress: true # 2 ???????????? IP ?????
